export const ADD_USER_INFO = `ADD_USER_INFO`;
export const ADD_USER_DETAILS = `ADD_USER_DETAILS`;

export const ADD_STUDENT_DATA = `ADD_STUDENT_DATA`;
export const DELETE_STUDENT_DATA = `DELETE_STUDENT_DATA`;
export const UPDATE_STUDENT_DATA = `UPDATE_STUDENT_DATA`;

export const LOGOUT = `LOGOUT`;
